version: '3.8'

services:
  n8n:
    build: .
    container_name: n8n-scraping
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
      - .:/project
    environment:
      - N8N_HOST=${SUBDOMAIN:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}/
      - GENERIC_TIMEZONE=Africa/Cairo
      - PROXY_URL=http://scraperapi:fbc96f6bf5b7cded47f5cb9299277ba5@proxy-server.scraperapi.com:8001
      - NODES_EXCLUDE=[]
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_RESTRICT_FILE_ACCESS_TO=
